---
- name: Rebuild initramfs
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true

- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: true

- name: Restart zramswap
  ansible.builtin.systemd:
    name: zramswap
    state: restarted
    enabled: true
  failed_when: false
