#!/usr/bin/env python3
"""Generate the committed reference docs under docs/.

Covers the parts docsible cannot: docsible documents roles, but this repo's
configuration surface is ansible/group_vars/all.yml -- the file the README tells
people to edit -- and docsible has no notion of it.

The group_vars comments are already written as prose explaining *why* each
setting exists. This lifts them rather than inventing new text, so the docs
cannot drift from the reasoning they describe: there is only one copy.

  gen-config-docs.py [--out docs]
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BANNER = ("<!-- Generated by scripts/gen-config-docs.py. Do not edit by hand; "
          "run `make docs-config`. -->\n\n")


def run(cmd, cwd=None):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=180, cwd=cwd)
        return r.stdout if r.returncode == 0 else ""
    except Exception:
        return ""


def parse_group_vars(path):
    """Pull top-level keys out of group_vars, each with the comment above it.

    Deliberately a line scanner rather than a YAML load: PyYAML discards
    comments, and the comments are the entire point here. Section banners
    (# ==== NAME ====) become headings.
    """
    sections, current = [], {"title": "General", "blurb": [], "items": []}
    comment, in_banner, banner_text = [], False, []

    for raw in path.read_text().splitlines():
        line = raw.rstrip()
        stripped = line.strip()

        # Section banner: "# ====..." then "#  TITLE" lines then "# ====..."
        if re.fullmatch(r"#\s*=+", stripped):
            if in_banner:
                in_banner = False
                title = banner_text[0].strip() if banner_text else "Section"
                if current["items"] or current["blurb"]:
                    sections.append(current)
                current = {"title": title,
                           "blurb": [t for t in banner_text[1:] if t.strip()],
                           "items": []}
                banner_text, comment = [], []
            else:
                in_banner, banner_text = True, []
            continue
        if in_banner:
            banner_text.append(re.sub(r"^#\s?", "", stripped))
            continue

        if stripped.startswith("#"):
            text = re.sub(r"^#\s?", "", stripped)
            # "--- APT: desktop -------" is a separator, not prose. Keep its
            # label as a heading and discard the rule, or it reads as garbage
            # in the middle of an explanation.
            div = re.fullmatch(r"-{2,}\s*(.*?)\s*-{2,}", text.strip())
            if div:
                label = div.group(1).strip()
                if label:
                    comment.append(f"**{label}**")
                continue
            comment.append(text)
            continue
        if not stripped or stripped == "---":
            if not stripped:
                comment = []
            continue

        m = re.match(r"^([a-zA-Z_][\w]*):(.*)$", line)
        if m:
            key, rest = m.group(1), m.group(2).strip()
            current["items"].append({
                "key": key,
                "inline": rest if rest and not rest.startswith(("#", ">", "|")) else "",
                "multiline": not rest or rest.startswith((">", "|")),
                "doc": [c for c in comment if c.strip()],
            })
            comment = []
        else:
            comment = []

    if current["items"] or current["blurb"]:
        sections.append(current)
    return sections


def md_configuration(sections):
    out = [BANNER, "# Configuration reference\n",
           "Every setting in `ansible/group_vars/all.yml`, with the explanation that "
           "accompanies it in the file. Edit that file, then either `make apply` "
           "(this machine) or `make image` (a new artifact).\n"]
    for sec in sections:
        out.append(f"\n## {sec['title'].title()}\n")
        if sec["blurb"]:
            out.append("\n".join(sec["blurb"]) + "\n")
        if not sec["items"]:
            continue
        for it in sec["items"]:
            value = f"`{it['inline']}`" if it["inline"] else "_(list or block — see the file)_"
            out.append(f"\n### `{it['key']}`\n\n{value}\n")
            if it["doc"]:
                out.append("\n" + "\n".join(it["doc"]) + "\n")
    return "".join(out)


def md_roles():
    roles_dir = REPO / "ansible" / "roles"
    rows = []
    for role in sorted(p for p in roles_dir.iterdir() if p.is_dir()):
        # From meta/main.yml, which states the role's purpose deliberately.
        # Deriving it from the first comment in tasks/main.yml truncated
        # mid-sentence, and for roles whose file opens with a task comment it
        # described that task rather than the role.
        meta = role / "meta" / "main.yml"
        summary = ""
        if meta.exists():
            m = re.search(r"^\s*description:\s*(.+?)\s*$", meta.read_text(), re.M)
            if m:
                summary = m.group(1)
        readme = "README.md" if (role / "README.md").exists() else None
        link = f"[{role.name}](../ansible/roles/{role.name}/README.md)" if readme else role.name
        rows.append(f"| {link} | {summary} |")
    return (BANNER + "# Ansible roles\n\n"
            "Per-role documentation is generated by [docsible](https://github.com/docsible/docsible) "
            "into a `README.md` inside each role directory, so it renders when browsing that "
            "directory. This index links to them.\n\n"
            "| Role | Purpose |\n|---|---|\n" + "\n".join(rows) + "\n")


def md_packer():
    """packer inspect already reports every variable and its default."""
    raw = run(["packer", "inspect", str(REPO / "packer")])
    if not raw:
        return BANNER + "# Packer\n\n_`packer inspect` unavailable when these docs were generated._\n"
    rows = []
    for line in raw.splitlines():
        m = re.match(r"^var\.([\w]+):\s*(.*)$", line.strip())
        if m:
            rows.append(f"| `{m.group(1)}` | {m.group(2)} |")
    return (BANNER + "# Packer build variables\n\n"
            "Inputs to `packer/`, with the defaults they take when not overridden. "
            "Override on the command line with `-var`, or in `packer/local.pkrvars.hcl` "
            "(gitignored; see `local.pkrvars.hcl.example`).\n\n"
            "| Variable | Default |\n|---|---|\n" + "\n".join(rows) + "\n")


def md_terraform():
    parts = [BANNER, "# Terraform modules\n"]
    have = run(["terraform-docs", "--version"])
    for mod in sorted((REPO / "terraform").iterdir()):
        if not mod.is_dir():
            continue
        parts.append(f"\n## `terraform/{mod.name}`\n\n")
        if have:
            parts.append(run(["terraform-docs", "markdown", "table", "--no-header", str(mod)])
                         or "_terraform-docs produced no output._\n")
        else:
            # Falling back rather than emitting nothing: a missing optional tool
            # should degrade the docs, not blank a whole section silently.
            parts.append("_terraform-docs not installed; showing declared variables._\n\n")
            for f in ("variables.tf", "outputs.tf"):
                src = mod / f
                if src.exists():
                    names = re.findall(r'^(variable|output)\s+"([^"]+)"', src.read_text(), re.M)
                    if names:
                        parts.append(f"\n**{f}**\n\n"
                                     + "\n".join(f"- `{n}`" for _, n in names) + "\n")
    return "".join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "docs"))
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)

    gv = REPO / "ansible" / "group_vars" / "all.yml"
    if not gv.exists():
        print(f"error: {gv} not found", file=sys.stderr)
        return 1

    written = {
        "configuration.md": md_configuration(parse_group_vars(gv)),
        "roles.md": md_roles(),
        "packer.md": md_packer(),
        "terraform.md": md_terraform(),
    }
    index = [BANNER, "# Documentation\n\n",
             "Generated from source by `make docs-config`. CI regenerates these and fails "
             "if the result differs, so they cannot silently go stale.\n\n",
             "| Document | Covers |\n|---|---|\n",
             "| [configuration.md](configuration.md) | Every setting in `group_vars/all.yml` |\n",
             "| [roles.md](roles.md) | Index of the Ansible roles |\n",
             "| [packer.md](packer.md) | Packer build variables |\n",
             "| [terraform.md](terraform.md) | Terraform module inputs and outputs |\n",
             "| [aws-s3-setup.md](aws-s3-setup.md) | Using a real AWS S3 bucket instead of the default R2 one |\n",
             "\nThe contents of a *built image* are documented separately, in the "
             "`docs.html` rendered beside each artifact by `scripts/render-docs.py`.\n",
             "\n`aws-s3-setup.md` is hand-written, not generated -- everything else "
             "in this table is produced from source by this script.\n"]
    written["README.md"] = "".join(index)

    for name, body in written.items():
        (out / name).write_text(body)
        print(f"  wrote {out.name}/{name} ({len(body.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
